### ISSUE TITLE
challenging .srt file?

### ISSUE THREAD

**Issue by intre4si32** [carsonip/Penguin-Subtitle-Player#50]
Weird but I 've met my first .srt which Penguin does not open.
If interested to check I linked it:
[https://ytssubtitles.com/aloys/tt5065810/514775](url)
It opens only when I uncheck **Use detected encoding**. It's only this particular srt to give the penguin fits.

**Comment by carsonip** [comment]
Thanks for reporting! I tried the file and it did not work. Your workaround gives useful info about the bug. I'll let you know when I found out the cause / fixed the bug.

**Comment by carsonip** [comment]
@intre4si32 May I know what system (and version) and what version (version number, statically compiled/from package manager, github/sourceforge etc) of penguin you are using?
As far as I know, the charset detector reports ascii as the charset of the srt file but ascii charset may not be in the system. That's why choosing UTF-8 manually works. A naive fix would be easy but I want to know whether this affects other missing charsets.
