### ISSUE TITLE
Flip subtitles

### ISSUE THREAD

**Issue by Clonewayx** [carsonip/Penguin-Subtitle-Player#54]
Allow vertically flip subtitles to be able to project from rear.

Thanks

**Comment by carsonip** [comment]
I haven't thought of this. Just out of curiosity: do you also flip the movie display upside down? Is it easier to do it in your operating system instead of having the software to support it? This feature isn't impossible to do but it just feels weird to do it at the application level. I can't imagine Chrome / Firefox has an option to flip the whole window content vertically.

**Comment by Clonewayx** [comment]
I want to make projection where peoples can watch from both sides of screen.

My fault I meant horizontal flip like these: ![](http://media.openclipart.org/people/Clon/800px-1529041935.png)

**Comment by carsonip** [comment]
I will be away from keyboard for a while, I'll take a look into this in July.

**Comment by carsonip** [comment]
It seems harder than I thought. Guess I will not implement this. If anyone could, feel free to submit a PR.
The closest I can find is this: http://www.qtcentre.org/archive/index.php/t-8248.html

**Comment by SamHamou** [comment]
[https://moopost.blogspot.com/2019/04/penguin-subtitle-player-10-released.html](https://moopost.blogspot.com/2019/04/penguin-subtitle-player-10-released.html)
